apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: sample-app
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1>Welcome to my sample app!</h1>
    </body>
    </html>
