apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: sample-app
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Add this line
  hostPath:
    path: /tmp/data
