apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: sample-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
